apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-redis-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-redis
  template:
    metadata:
      labels:
        app: expiration-redis
    spec:
      containers:
        - name: expiration-redis-container
          image: redis

---
# service configuration to target and expose auth pods
# we dont even mention anything about the deployment here
apiVersion: v1
kind: Service
metadata:
  name: expiration-redis-svc
spec:
  selector:
    app: expiration-redis
  ports:
    - name: expiration-redis-port # name of the port - can be used for identification, if a service is exposing other ports of a pod
      protocol: TCP
      port: 6379
      targetPort: 6379
