apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: pranavsrivatsav/ticketing-expiration
          imagePullPolicy: Never
          env:
            - name: REDIS_URI
              value: "http://expiration-redis-svc:6379"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_URL
              value: "http://nats-streaming-svc:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name #copies the pod name
                  # - which is a more meaningful unique client id than just a random string
# We dont nedd to expose expiration service. It runs based on NATS events and responds with NATS events
# None of the services communicate with expiration service directly
