apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-streaming-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-streaming
  template:
    metadata:
      labels:
        app: nats-streaming
    spec:
      containers:
        - name: nats-streaming-container
          image: nats-streaming:0.17.0
          args: [
              "-p", # client port
              "4222",
              "-m", # monitoring port
              "8222",
              "-hbi", # heart beat ping frequency
              "5s",
              "-hbt", # heart beat ping back wait time
              "5s",
              "-hbf", # allowed heart beat failures
              "2",
              "-SD",
              "-cid", # cluster id
              "ticketing",
            ]

---
# service configuration to target and expose auth pods
# we dont even mention anything about the deployment here
apiVersion: v1
kind: Service
metadata:
  name: nats-streaming-svc
spec:
  selector:
    app: nats-streaming
  ports:
    - name: client # name of the port - can be used for identification, if a service is exposing other ports of a pod
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
