apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongodb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongodb
  template:
    metadata:
      labels:
        app: tickets-mongodb
    spec:
      containers:
        - name: auth-tickets-container
          image: mongo

---
# service configuration to target and expose auth pods
# we dont even mention anything about the deployment here
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongodb-svc
spec:
  selector:
    app: tickets-mongodb
  ports:
    - name: tickets-mongodb-port # name of the port - can be used for identification, if a service is exposing other ports of a pod
      protocol: TCP
      port: 27017
      targetPort: 27017
