apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: pranavsrivatsav/ticketing-payments
          imagePullPolicy: Always
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RZP_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: rzp-public-key
                  key: RZP_PUBLIC_KEY
            - name: RZP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: rzp-private-key
                  key: RZP_PRIVATE_KEY
            - name: MONGO_URI
              value: "mongodb://payments-mongodb-svc:27017/orders"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_URL
              value: "http://nats-streaming-svc:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name #copies the pod name
                  # - which is a more meaningful unique client id than just a random string

---
# service configuration to target and expose auth pods
# we dont even mention anything about the deployment here
apiVersion: v1
kind: Service
metadata:
  name: payments-svc
spec:
  selector:
    app: payments
  ports:
    - name: payments # name of the port - can be used for identification, if a service is exposing other ports of a pod
      protocol: TCP
      port: 3000
      targetPort: 3000
