name: deploy-auth

# event on which this workflow should be executed
on:
  push:
    branches:
      - master
    paths: # Trigger workflow only if changes are present in auth folder
      - "auth/**"

jobs:
  build:
    environment: PROD
    runs-on: ubuntu-latest # operating system to use
    steps:
      - uses: actions/checkout@v2 # inbuilt action available to checkout the branch
      - run: cd auth && docker build -t pranavsrivatsav/ticketing-auth . # build the image
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: # load our secrets as environment variables to be accessed by our scripts above
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push pranavsrivatsav/ticketing-auth # push image to docker hub
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ddb24b32-3c81-4682-a8e0-962929208cff
      - run: kubectl rollout restart deployment auth-depl
